### ISSUE TITLE
Patch for Archer C50

### ISSUE THREAD

**Issue by waschmi** [lede-project/source#10]
Hi. Can someone take over integration of it? This Patch applies to new Build System but the DTS part probably needs rework and I rather not touch this myself.
[0001-Archer-C50.patch.txt](https://github.com/lede-project/source/files/264553/0001-Archer-C50.patch.txt)

**Comment by blogic** [comment]
i have a C50 sitting on my desk, i'll have a look at this the next couple of days

**Comment by jow-** [comment]
@waschmi - we'll need your real name and mail in order to properly acknowledge when pushing the commit.

**Comment by waschmi** [comment]
@jow- according to this post http://openrouter.info/forum/viewtopic.php?f=18&t=4001 the Archer C50 port was done by [Heinz] based on Archer C20i port done by blogic ( https://dev.openwrt.org/changeset/46348 ). Also with [Heinz], [obsy] ( http://dl.eko.one.pl/test/c50/ ) and anonymous (https://dev.openwrt.org/ticket/22034).  I didn't do anything worthwhile and since blogic is the initial author anyway, it should be okay if his name will be used,

**Comment by jow-** [comment]
@waschmi - I see, thank you for the additional context!

**Comment by waschmi** [comment]
@jow- corrected by previous comment

**Comment by blogic** [comment]
we cannot really accept the patch like this. it needs to be sent via a PR with a SoB. if the original submission did not have this that that is an akward situation. i'll close the issue and hope we get a  proper PR. if not then i will eventually get around to porting the unit i have on my desk.
