### ISSUE TITLE
Warning Message from github repository

### ISSUE THREAD

**Issue by gwlim** [lede-project/source#104]
I am getting following error message when working with a git clone of this repository during make etc
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.

**Comment by blogic** [comment]
the tags are missing. how did you clone the repo ?

**Comment by gwlim** [comment]
git clone https://github.com/lede-project/source.git --depth=1

**Comment by blogic** [comment]
dont do a shallow clone, that will fix your problem.

**Comment by blogic** [comment]
i am afraid not. we'll see if we can fix it somehow.

**Comment by thess** [comment]
Not sure if John fixed it or something else. This works fine for me.

**Comment by gwlim** [comment]
Yes it is fixed no longer get error messages doing shallow clone
