### ISSUE TITLE
Router drops off network with WAN DHCP release on reboot disabled, using sysupgrade

### ISSUE THREAD

**Issue by kdarbyshirebryant** [lede-project/source#107]
I'm seeing some very bizarre sysupgrade/network behaviour that appears to be as a result of this commit: https://git.lede-project.org/?p=source.git;a=commit;h=f9a3123bbf628906b0a583ad9c3e306a8bb5e2b2 

After doing a sysupgrade my Archer C7 v2 will briefly (for around 10 seconds) respond to LAN access, pings etc, and then simply stop talking to the network.  No LAN response to pings on either wireless or wired, no WAN response.  Eventually my ISP in some way prompts something (DHCP release?) at which point the router responds on WAN & LAN - this can take up to 60 minutes.  A manual power off/on cycle also restores correct behaviour.

If I set 'option release '1'' in /etc/config/network for the WAN interface then sysupgrade behaviour is ok, the router reboots, responds and continues to respond to LAN & WAN.

I should add that I used DHCPv4 on the WAN, with a clientID required by the ISP

netifd race condition?

**Comment by jow-** [comment]
Maybe something is blocking the boot? Do you have any chance to debug this via serial? Or did you try to reach the device via IPv6 link local while it is in the defunct state?

**Comment by kdarbyshirebryant** [comment]
Good point, will try IPv6 link local next time.  Have USB ->serial 3v3 adapter so that's stage 2 if needed.  Will be a few days.

**Comment by kdarbyshirebryant** [comment]
More info:  ipv6 linklocal ssh works. So have a 'logread', 'ip address' output.
on router 'pings' to its local IPv4 fail as does 127.0.0.1 - sendto operation not permitted.
Shutdown the firewall and everything sprung into life.  Restarted firewall..everything still ok.

**Comment by kdarbyshirebryant** [comment]
It appears to be bearDropper.  It was trying to play with firewall rules whilst fw3 was doing stuff in response to interfaces coming up.  Delayed bearDropper start a bit more (sleep 10) as a horridly simplistic workaround.
