### ISSUE TITLE
rtc-pcf8563 gets loaded too late durinng boot

### ISSUE THREAD

**Issue by neheb** [lede-project/source#116]
During boot I see

[    3.060000] hctosys: unable to open rtc device (rtc0)

but later on I see

[   23.020000] rtc-pcf8563 0-0051: chip found, driver version 0.4.4
[   23.030000] rtc-pcf8563 0-0051: low voltage detected, date/time is not reliable.
[   23.050000] rtc-pcf8563 0-0051: rtc core: registered rtc-pcf8563 as rtc0

Ignoring the low voltage error(which seems to go away after enough uptime), does this mean that openwrt doesn't really use the hardware clock?

This is on an MQMaker WiTi device.

**Comment by blogic** [comment]
yes it uses the hwclock. time gets applied by /etc/init.d/sysfixtime
