### ISSUE TITLE
WAN is broken in the latest build

### ISSUE THREAD

**Issue by miltador** [lede-project/source#117]
Device: TP-Link WR842ND v1
WAN is not functional with the latest build, I guess it is broken by [1beb5be](https://github.com/lede-project/source/commit/1beb5bec6453abb220c5be4ddb9e6dc02d08d735) commit.
Both DHCP and Static address connections do not work on WAN interface.

**Comment by jow-** [comment]
@nbd168

**Comment by nbd168** [comment]
Reverted that commit, will need to refine the checks to deal with the issue that it fixes.
