### ISSUE TITLE
nslookup: can't resolve

### ISSUE THREAD

**Issue by davidc502** [lede-project/source#123]
Issue shows itself from command line or LuCi Diagnostics page. Flashed back to stock, and then back to lede to be sure it wasn't a configuration issue I caused. 

root@lede:~# nslookup dev.openwrt.org
nslookup: can't resolve '(null)': Name does not resolve

Name:      dev.openwrt.org
Address 1: 217.115.15.26 dev.openwrt.nanl.de
Address 2: 2a00:1328:e000:452::26

However running the following command will work.

root@lede:~# nslookup dev.openwrt.org localhost    <<< Added localhost for local lookup.
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      dev.openwrt.org
Address 1: 217.115.15.26 dev.openwrt.nanl.de
Address 2: 2a00:1328:e000:452::26

This issue appears to affect Dynamic DNS.

**Comment by davidc502** [comment]
For those who need a work around.This also temporarily fixes Dynamic DNS which depends on nslookup.

Remove the symbolic link nslookup in /usr/bin

Put the following command in a script and place it in /usr/bin
Don't forget to make it executable.

/bin/busybox nslookup $1 localhost

name server lookups work properly
.
root@lede:~# nslookup google.com
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      google.com
Address 1: 74.125.196.102 yk-in-f102.1e100.net
Address 2: 74.125.196.113 yk-in-f113.1e100.net
Address 3: 74.125.196.100 yk-in-f100.1e100.net
Address 4: 74.125.196.138 yk-in-f138.1e100.net
Address 5: 74.125.196.139 yk-in-f139.1e100.net
Address 6: 74.125.196.101 yk-in-f101.1e100.net
Address 7: 2607:f8b0:4002:c07::65 yk-in-x65.1e100.net

**Comment by hnyman** [comment]
This sounds like the musl - busybox nslookup incompatibility (regarding the server parameter, both using it and displaying it).

https://dev.openwrt.org/ticket/18333
https://dev.openwrt.org/ticket/20893

**Comment by davidc502** [comment]
Just compiled lede r1003 and the issue is still there. Does anyone know if it is being looked at?

**Comment by thess** [comment]
Issue moved to [FS#155](https://bugs.lede-project.org/index.php?do=details&task_id=155)
