### ISSUE TITLE
RST packet as response to SYN is not forwarded to sender?

### ISSUE THREAD

**Issue by xnoreq** [lede-project/source#139]
Following setup:
A host on the LAN sends a SYN packet through the router to a remote server. The server rejects it with tcp-reset.
tcpdump on the router shows the SYN packet being sent and the RST,ACK packet being received over eth0.2 (WAN interface), but the packet never makes it to the host on the LAN.

In iptables the reset packet shows up in -t mangle PREROUTING and then INPUT instead of FORWARD. Why?

I've tried disabling the firewall (all iptables flushed) and just added a single MASQUERADE rule ... same result.
This is on 15.05.1 with Linux 3.18.23.

**Comment by jow-** [comment]
Maybe ICMP redirects are involved. Did you try a current lede build though?

**Comment by xnoreq** [comment]
No, also:
`# tcpdump -i eth0.2 -n port 41111 or icmp`
`tcpdump: verbose output suppressed, use -v or -vv for full protocol decode`
`listening on eth0.2, link-type EN10MB (Ethernet), capture size 65535 bytes`
`00:19:17.424876 IP wanip.3133 > serverip.41111: Flags [S], seq 1201767743, win 65535, options [mss 1460,nop,wscale 2,nop,nop,sackOK], length 0`
`00:19:17.447097 IP serverip.41111 > wanip.3133: Flags [R.], seq 0, ack 1201767744, win 0, length 0`

**Comment by xnoreq** [comment]
Maybe someone can reproduce this issue?

**Comment by thess** [comment]
Issue moved to [FS#151](https://bugs.lede-project.org/index.php?do=details&task_id=151)
