### ISSUE TITLE
Archer C7 v2 missing ath10k

### ISSUE THREAD

**Issue by plumpudding** [lede-project/source#154]
The Archer C7 v2 binaries are missing the kmod-ath10k and ath10k-firmware-qca988x packages for the 5GHz phy to work properly.

**Comment by ds2k5** [comment]
May this can help you

vi ../source/.config
Relpace: # CONFIG_PACKAGE_kmod-ath10k is not set
to:  CONFIG_PACKAGE_kmod-ath10k=y

make menuconfig -> save
make

**Comment by plumpudding** [comment]
I use the imagebuilder. I can solve the problem by manually adding kmod-ath10k package. It should be default though. 

On June 29, 2016 11:59:38 AM GMT+02:00, ds2k5 <notifications@github.com> wrote:
>May this can help you
>
>vi ../source/.config
>Relpace: # CONFIG_PACKAGE_kmod-ath10k is not set
>to:  CONFIG_PACKAGE_kmod-ath10k=y
>
>make menuconfig -> save
>make
>
>
>
>
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lede-project/source/issues/154#issuecomment-229312569

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by blogic** [comment]
@nbd168 the DEVICE_PACKAGES variable lists the module. please check why IB fails to include it

**Comment by nbd168** [comment]
Fixed in current snapshots
