### ISSUE TITLE
libubox.git | Could not resolve host | 404 Not Found

### ISSUE THREAD

**Issue by ds2k5** [lede-project/source#156]
Hi,

try to build the Image for " TP Link Archer C7 v2 "

make -j1 V=s   Output:

fatal: unable to access 'https://git.lede-project.org/project/libubox.git/': Could not resolve host: git.lede-project.org
make[3]: *** [Makefile:96: /home/user01/lede/source/dl/libubox-2016-06-15-c2f2c47f3e9a2d709ec82a79f6fadd3124c18781.tar.gz] Error 128
make[3]: Leaving directory '/home/user01/lede/source/package/libs/libubox'
make[2]: *** [package/Makefile:188: package/libs/libubox/compile] Error 2
make[2]: Leaving directory '/home/user01/lede/source'
make[1]: *** [package/Makefile:184: /home/user01/lede/source/staging_dir/target-mips_34kc_musl-1.1.14/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/user01/lede/source'
make: *** [/home/user01/lede/source/include/toplevel.mk:195: world] Fehler 2

if i open the URL https://git.lede-project.org/project/libubox.git
got this error: 404 Not Found

**Comment by jow-** [comment]
The 404 is normal, the "Could not resolve host" error looks like an intermediate connection problem on your side?

**Comment by ds2k5** [comment]
sorry i for got... got this error in browser... but i have access to internet

**Comment by jow-** [comment]
Then simply retry: `make package/libubox/compile V=s`

**Comment by ds2k5** [comment]
ok thanks.... you are right....
did not work behind a proxy :-(

**Comment by jow-** [comment]
I hope you got it working now!

**Comment by ds2k5** [comment]
no !

fatal: unable to access 'https://git.lede-project.org/project/libubox.git/': Failed to connect to git.lede-project.org port 443: Connection refused

**Comment by ds2k5** [comment]
sorry .... it works .... need to use ProxyChains for this case! THANKS
