### ISSUE TITLE
TP Link WR841ND Ver. 8.2 - no space left on device

### ISSUE THREAD

**Issue by ds2k5** [lede-project/source#158]
Hello,
build the Image for WR841ND V8 an install it on the Device.
But if try to install Luci got error.

root@lede:~# opkg install luci

Installing luci (git-16.180.53022-d417632-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/mips_34kc/luci/luci_git-16.180.53022-d417632-1_all.ipk.
Installing luci-theme-bootstrap (git-16.180.53022-d417632-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/mips_34kc/luci/luci-theme-bootstrap_git-16.180.53022-d417632-1_all.ipk.
Installing luci-app-firewall (git-16.180.53022-d417632-1) to root...
Configuring luci-theme-bootstrap.
Collected errors:
 * verify_pkg_installable: Only have 0kb available on filesystem /overlay, pkg luci-app-firewall needs 11
 * opkg_install_cmd: Cannot install package luci.

root@lede:~# opkg install luci
Installing luci (git-16.180.53022-d417632-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/mips_34kc/luci/luci_git-16.180.53022-d417632-1_all.ipk.
Installing luci-app-firewall (git-16.180.53022-d417632-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/mips_34kc/luci/luci-app-firewall_git-16.180.53022-d417632-1_all.ipk.
Installing luci-proto-ppp (git-16.180.53022-d417632-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/mips_34kc/luci/luci-proto-ppp_git-16.180.53022-d417632-1_all.ipk.
Configuring luci-app-firewall.
Collected errors:
 * wfopen: /usr/lib/lua/luci/model/cbi/admin_network/proto_pptp.lua: No space left on device.
 * extract_archive: Cannot make dir /usr/lib/lua/luci/model/network/: No space left on device.
 * wfopen: /usr/lib/lua/luci/model/network/proto_ppp.lua: No such file or directory.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-proto-ppp.list: No space left on device.
 * opkg_install_pkg: Failed to extract data files for luci-proto-ppp. Package debris may remain!
 * opkg_install_cmd: Cannot install package luci.
 * opkg_conf_write_status_files: Can't open status file //usr/lib/opkg/status: No space left on device.

root@lede:~# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 2.0M      2.0M         0 100% /rom
tmpfs                    13.7M    628.0K     13.1M   4% /tmp
/dev/mtdblock3          704.0K    648.0K     56.0K  92% /overlay
overlayfs:/overlay      704.0K    648.0K     56.0K  92% /
tmpfs                   512.0K         0    512.0K   0% /dev

How to fix this ?

root@lede:~# netstat -tuln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      
tcp        0      0 :::80                   :::*                    LISTEN      
tcp        0      0 :::53                   :::*                    LISTEN      
tcp        0      0 :::22                   :::*                    LISTEN      
udp        0      0 0.0.0.0:53              0.0.0.0:*                           
udp        0      0 0.0.0.0:67              0.0.0.0:*                           
udp        0      0 :::546                  :::*                                
udp        0      0 :::547                  :::*                                
udp        0      0 :::53                   :::*                        

If open in Browser: http://192.168.10.1/cgi-bin/luci
got this Error:

Bad Gateway
The process did not produce any response

**Comment by blogic** [comment]
we cannot fix the fact that your router has to little flash to hold luci outside the squashfs area. i'll start a discussion about adding luci to the snapshot images.
