### ISSUE TITLE
[solved] Archer C7 v2 - no Wireless Intefaces

### ISSUE THREAD

**Issue by ds2k5** [lede-project/source#162]
Hello,
i build a Image for TP Link Archer C7 v2 with Luci ( see .config as config.txt )
But there a no wireless Interfaces.
What did i wrong ?
The Wireless Switch at the device is ON
Thanks
[archer-c7-v2_dmesg.txt](https://github.com/lede-project/source/files/340860/archer-c7-v2_dmesg.txt)
[archer-c7-v2_ifconfig.txt](https://github.com/lede-project/source/files/340861/archer-c7-v2_ifconfig.txt)
[archer-c7-v2_lsmod.txt](https://github.com/lede-project/source/files/340862/archer-c7-v2_lsmod.txt)
![archer-c7-v2_luci](https://cloud.githubusercontent.com/assets/11292286/16479751/9c9e9e62-3ea2-11e6-90f0-e8f4fc8fda85.png)
[config.txt](https://github.com/lede-project/source/files/340865/config.txt)

**Comment by jow-** [comment]
Can you provide the output of `iw list` ?

**Comment by jow-** [comment]
Ok so the wifi driver initialized at least. Can you paste the last 30 lines or so of `logread` after you issued a `wifi up` on the terminal?

**Comment by ds2k5** [comment]
here it is
[archer-c7-v2_logread.txt](https://github.com/lede-project/source/files/341022/archer-c7-v2_logread.txt)

**Comment by jow-** [comment]
The `INVALID_WPA_PSK` in your log means that your provided wifi password is shorter than 8 characters - can you try one which is at least 8 characters long?

**Comment by ds2k5** [comment]
No, my password is: 64 charters long (lower, uppercase, numbers and special charters ( example !&$§ )

in /etc/config/wireless i can see the password
in the line: 	option password 
us WPA2-PSK

**Comment by blogic** [comment]
does it work if you use 01234567 as a password ?

**Comment by jow-** [comment]
64 characters is too long :) If your PSK is exactly 64 byte it must be in hexadecimal notation (e.g. as generated by the `wpa_passphrase` command.) Plaintext passwords must be between 8 and 63 chars.

**Comment by ds2k5** [comment]
thanks jow and blogic

i found the issue. 2,4 GHZ is working now (with my long password)
I need to add the password at the line: option key
the WebGUI looks diffrent since reboot.
Don't know why. Before there are lines for raduis server etc. but i selected wpa2-psk

@jow: sorry - my password is 63 chrarters not 64!

Sorry guys!
