### ISSUE TITLE
TP Link TL-WR941ND V 6.0 - no Wireless interfaces

### ISSUE THREAD

**Issue by ds2k5** [lede-project/source#164]
Hello,
on a TL-WR941ND V 6.0 dit not have a wireless interface.

root@lede:/# iw list
root@lede:/# 

[    9.354012] ath9k qca956x_wmac: failed to initialize device
[    9.359833] ath9k: probe of qca956x_wmac failed with error -22

[tl-wr941dn_dmesg.txt](https://github.com/lede-project/source/files/341198/tl-wr941dn_dmesg.txt)

[tl-wr941dn_lsmod.txt](https://github.com/lede-project/source/files/341201/tl-wr941dn_lsmod.txt)

What did i wrong ?

**Comment by blogic** [comment]
[    9.256835] ath: phy0: eeprom contains invalid mac address: ef:ff:bf:af:5f:7f
[    9.264289] ath: phy0: random mac address will be used: 3e:30:f7:7c:16:51
[    9.272876] ath: EEPROM regdomain: 0xefaf
[    9.272884] ath: EEPROM indicates we should expect a country code
[    9.272904] ath: invalid regulatory domain/country code 0xafaf
[    9.272911] ath: Invalid EEPROM contents
[    9.276998] ath9k qca956x_wmac: failed to initialize device

the eeprom is not loaded correctly. can you paste the output of "hexdump -C /dev/mtd4" please

**Comment by ds2k5** [comment]
sure
here it is
[tl-wr941dn_hexdump.zip](https://github.com/lede-project/source/files/341228/tl-wr941dn_hexdump.zip)

**Comment by blogic** [comment]
that is not a valid art partition how did you flash the unit ? i think you overwrote the art data somehow

**Comment by ds2k5** [comment]
serial console
open bootloader ( tpl )

and with running lede with sysupdate -v lede-ar71xx-generic-tl-wr941nd-v6-squashfs-factory.bin

how can i restore the /dev/mtd4 partition ?

i tryed to flash the orginal firmware an then: lede-ar71xx-generic-tl-wr941nd-v6-squashfs-factory.bin
but did't chance anything

**Comment by blogic** [comment]
by flashing the factory image you overwrote the art data. this is irreversible. factory images are used to flash via the stock webui. you should have just flashed the sysupgrade image via uboot i am afraid. there is nothing we can do to recreate the art data. the device is a doorstopper or paperweight now.

**Comment by ds2k5** [comment]
i understand 

shit, and if sombody has the same model can export the partition with dd
and write this with dd on my device - not possible ?

**Comment by blogic** [comment]
On 30/06/2016 13:11, ds2k5 wrote:
> i understand
> 
> shit, and if sombody has the same model can export the partition with dd
> and write this with dd on my device - not possible ?
> 
> 
not possible i am afraid, the art data is device specific. it holds the
calibration data of your specific unit i am afraid.

**Comment by ds2k5** [comment]
ok but if it is a doorstopper i can try it!
any idea find a guy that had a WR941ND with LEDE to export the mtd4 partiton ?

**Comment by blogic** [comment]
try asking on the mailing list
