### ISSUE TITLE
Famous issue: rt2x00queue_write_tx_frame: Error - Dropping frame due to full tx queue 2

### ISSUE THREAD

**Issue by Cjcr** [lede-project/source#194]
Hello,

First, congrats for the new project! :-)

Second, any way to fix the famous **`rt2x00queue_write_tx_frame: Error - Dropping frame due to full tx queue 2`** in MediaTek **MT7620**n devices?

More related info here:

https://dev.openwrt.org/ticket/12313
https://dev.openwrt.org/ticket/14744
https://dev.openwrt.org/ticket/17556

I have the Nexx WT3020 with the problem (https://wiki.openwrt.org/toh/nexx/wt3020) but it affects much more devices!

Regards.

**Comment by jow-** [comment]
There is no dedicated maintainer for rt2x00 either in OpenWrt or LEDE so it is unlikely to receive OpenWrt or LEDE specific fixes. The best course of action would be to report that errors upstream at linux-wireless.

**Comment by Cjcr** [comment]
It seems that is already reported to the linux kernel: https://bugzilla.kernel.org/show_bug.cgi?id=82751

**Comment by thess** [comment]
Issue moved to [FS#152](https://bugs.lede-project.org/index.php?do=details&task_id=152)
