### ISSUE TITLE
TL-MR3020 wireless driver error on R958

### ISSUE THREAD

**Issue by tomudo** [lede-project/source#195]
Build - R958 show error message after booting and start wireless. Here is error log.

[    0.000000] Linux version 4.4.14 (buildbot@builds) (gcc version 5.3.0 (LEDE G                                                                                                                      CC 5.3.0 r915) ) #1 Tue Jul 12 22:42:48 UTC 2016
[    0.000000] MyLoader: sysp=9f4ee02d, boardp=d90f4259, parts=c1914066
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 revision is: 00019374 (MIPS 24Kc)
[    0.000000] SoC: Atheros AR9330 rev 1
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 04000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] No valid device tree found, continuing without
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000003ffffff]
[    0.000000] On node 0 totalpages: 16384
[    0.000000] free_area_init_node: node 0, pgdat 804265d0, node_mem_map 8100000                                                                                                                      0
[    0.000000]   Normal zone: 128 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 16384 pages, LIFO batch:3
[    0.000000] Primary instruction cache 64kB, VIPT, 4-way, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 4-way, VIPT, cache aliases, linesize 32                                                                                                                       bytes
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pag                                                                                                                      es: 16256
[    0.000000] Kernel command line:  board=TL-MR3020  console=ttyATH0,115200 roo                                                                                                                      tfstype=squashfs,jffs2 noinitrd
[    0.000000] PID hash table entries: 256 (order: -2, 1024 bytes)
[    0.000000] Dentry cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Inode-cache hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Writing ErrCtl register=00000000
[    0.000000] Readback ErrCtl register=00000000
[    0.000000] Memory: 60032K/65536K available (3058K kernel code, 161K rwdata,                                                                                                                       768K rodata, 292K init, 205K bss, 5504K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS:51
[    0.000000] Clocks: CPU:400.000MHz, DDR:400.000MHz, AHB:200.000MHz, Ref:25.00                                                                                                                      0MHz
[    0.000000] clocksource: MIPS: mask: 0xffffffff max_cycles: 0xffffffff, max_i                                                                                                                      dle_ns: 9556302233 ns
[    0.000014] sched_clock: 32 bits at 200MHz, resolution 5ns, wraps every 10737                                                                                                                      418237ns
[    0.007549] Calibrating delay loop... 265.42 BogoMIPS (lpj=1327104)
[    0.088738] pid_max: default: 32768 minimum: 301
[    0.093349] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.099498] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.110084] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, ma                                                                                                                      x_idle_ns: 19112604462750000 ns
[    0.119423] NET: Registered protocol family 16
[    0.124392] MIPS: machine is TP-LINK TL-MR3020
[    0.398290] clocksource: Switched to clocksource MIPS
[    0.403752] NET: Registered protocol family 2
[    0.407879] TCP established hash table entries: 1024 (order: 0, 4096 bytes)
[    0.413278] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.419321] TCP: Hash tables configured (established 1024 bind 1024)
[    0.425499] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.430983] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.437324] NET: Registered protocol family 1
[    0.441193] PCI: CLS 0 bytes, default 32
[    0.442604] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.471132] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.475352] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORIT                                                                                                                      Y) (c) 2001-2006 Red Hat, Inc.
[    0.488383] io scheduler noop registered
[    0.490770] io scheduler deadline registered (default)
[    0.496017] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[    0.506011] ar933x-uart: ttyATH0 at MMIO 0x18020000 (irq = 11, base_baud = 15                                                                                                                      62500) is a AR933X UART
[    0.513879] console [ttyATH0] enabled
[    0.520660] bootconsole [early0] disabled
[    0.535214] m25p80 spi0.0: found s25fl064k, expected m25p80
[    0.539434] m25p80 spi0.0: s25fl064k (8192 Kbytes)
[    0.545542] 5 tp-link partitions found on MTD device spi0.0
[    0.549735] Creating 5 MTD partitions on "spi0.0":
[    0.554455] 0x000000000000-0x000000020000 : "u-boot"
[    0.561490] 0x000000020000-0x00000016e2f8 : "kernel"
[    0.567208] 0x00000016e2f8-0x0000007f0000 : "rootfs"
[    0.573016] mtd: device 2 (rootfs) set to be root filesystem
[    0.577302] 1 squashfs-split partitions found on MTD device rootfs
[    0.583475] 0x000000350000-0x0000007f0000 : "rootfs_data"
[    0.591090] 0x0000007f0000-0x000000800000 : "art"
[    0.596610] 0x000000020000-0x0000007f0000 : "firmware"
[    0.619014] libphy: ag71xx_mdio: probed
[    1.210006] ag71xx ag71xx.0: connected to PHY at ag71xx-mdio.1:04 [uid=004dd0                                                                                                                      41, driver=Generic PHY]
[    1.218801] eth0: Atheros AG71xx at 0xb9000000, irq 4, mode:MII
[    1.226728] NET: Registered protocol family 10
[    1.235137] NET: Registered protocol family 17
[    1.238220] bridge: automatic filtering via arp/ip/ip6tables has been depreca                                                                                                                      ted. Update your scripts to load br_netfilter if you need this.
[    1.250866] Bridge firewalling registered
[    1.254880] 8021q: 802.1Q VLAN Support v1.8
[    1.269129] VFS: Mounted root (squashfs filesystem) readonly on device 31:2.
[    1.276999] Freeing unused kernel memory: 292K (80447000 - 80490000)
[    2.693864] init: Console is alive
[    2.696093] init: - watchdog -
[    4.028892] usbcore: registered new interface driver usbfs
[    4.033036] usbcore: registered new interface driver hub
[    4.038427] usbcore: registered new device driver usb
[    4.050900] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    4.058194] ehci-platform: EHCI generic platform driver
[    4.062183] ehci-platform ehci-platform: EHCI Host Controller
[    4.067754] ehci-platform ehci-platform: new USB bus registered, assigned bus                                                                                                                       number 1
[    4.077757] ehci-platform ehci-platform: irq 3, io mem 0x1b000000
[    4.098345] ehci-platform ehci-platform: USB 2.0 started, EHCI 1.00
[    4.104479] hub 1-0:1.0: USB hub found
[    4.107338] hub 1-0:1.0: 1 port detected
[    4.115099] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    4.121976] ohci-platform: OHCI generic platform driver
[    4.130508] init: - preinit -
[    4.695640] usb 1-1: new high-speed USB device number 2 using ehci-platform
[    4.852114] random: procd urandom read with 8 bits of entropy available
[    4.901129] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    7.379779] eth0: link up (100Mbps/Full duplex)
[    7.382897] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    8.188534] jffs2_scan_eraseblock(): End of filesystem marker found at 0x5000                                                                                                                      0
[    8.194342] jffs2_build_filesystem(): unlocking the mtd device... done.
[    8.200904] jffs2_build_filesystem(): erasing all blocks after the end marker                                                                                                                      ... done.
[   19.445771] jffs2: notice: (383) jffs2_build_xattr_subsystem: complete buildi                                                                                                                      ng xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0                                                                                                                       orphan) found.
[   19.462522] mount_root: overlay filesystem has not been fully initialized yet
[   19.572856] mount_root: switching to jffs2 overlay
[   25.365383] urandom-seed: Seed file not found (/etc/urandom.seed)
[   25.639766] eth0: link down
[   25.656812] procd: - early -
[   25.658599] procd: - watchdog -
[   26.359466] procd: - ubus -
[   26.414166] procd: - init -
[   28.213577] ip6_tables: (C) 2000-2006 Netfilter Core Team
[   28.239690] Loading modules backported from Linux version wt-2016-06-20-0-gbc                                                                                                                      17424
[   28.245805] Backport generated by backports.git backports-20160216-7-g5735958
[   28.257636] ip_tables: (C) 2000-2006 Netfilter Core Team
[   28.277109] nf_conntrack version 0.5.0 (942 buckets, 3768 max)
[   28.331190] xt_time: kernel timezone is -0000
[   28.441056] PPP generic driver version 2.4.2
[   28.447679] NET: Registered protocol family 24
[   28.513187] ath: EEPROM regdomain: 0x0
[   28.513220] ath: EEPROM indicates default country code should be used
[   28.513233] ath: doing EEPROM country->regdmn map search
[   28.513263] ath: country maps to regdmn code: 0x3a
[   28.513279] ath: Country alpha2 being used: US
[   28.513293] ath: Regpair used: 0x3a
[   28.525344] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
[   28.530552] ieee80211 phy0: Atheros AR9330 Rev:1 mem=0xb8100000, irq=2
[   37.752446] device eth0 entered promiscuous mode
[   37.754534] IPv6: ADDRCONF(NETDEV_UP): br-lan: link is not ready
[   38.699243] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   40.139855] eth0: link up (100Mbps/Full duplex)
[   40.139958] br-lan: port 1(eth0) entered forwarding state
[   40.140049] br-lan: port 1(eth0) entered forwarding state
[   40.141869] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   41.627461] wlan0: authenticate with xx:xx:xx:xx:xx:xx
[   41.639348] wlan0: send auth to xx:xx:xx:xx:xx:xx (try 1/3)
[   41.641266] wlan0: authenticated
[   41.648595] wlan0: associate with xx:xx:xx:xx:xx:xx (try 1/3)
[   41.655487] wlan0: RX AssocResp from xx:xx:xx:xx:xx:xx (capab=0x411 status=0                                                                                                                       aid=1)
[   41.655823] ------------[ cut here ]------------
[   41.655898] WARNING: CPU: 0 PID: 32 at compat-wireless-2016-06-20/drivers/net                                                                                                                      /wireless/ath/ath9k/beacon.c:642 ath9k_calculate_summary_state+0x250/0x60c [ath9                                                                                                                      k]()
[   41.655914] Modules linked in: ath9k ath9k_common pppoe ppp_async iptable_nat                                                                                                                       ath9k_hw ath pppox ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4                                                                                                                       mac80211 ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_state xt_nat xt                                                                                                                      _multiport xt_mark xt_mac xt_limit xt_id xt_conntrack xt_comment xt_TCPMSS xt_RE                                                                                                                      DIRECT xt_LOG xt_CT slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 n                                                                                                                      f_nat nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_ra                                                                                                                      w iptable_mangle iptable_filter ip_tables crc_ccitt compat ledtrig_usbdev ip6t_R                                                                                                                      EJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_raw ip6table_mangle ip6t                                                                                                                      able_filter ip6_tables x_tables ohci_platform ohci_hcd ehci_platform ehci_hcd gp                                                                                                                      io_button_hotplug usbcore nls_base usb_common
[   41.656220] CPU: 0 PID: 32 Comm: kworker/u2:2 Not tainted 4.4.14 #1
[   41.656436] Workqueue: phy0 ieee80211_ibss_leave [mac80211]
[   41.656449] Stack : 83bc498c 83358b20 82d18c54 800a6834 838b1180 80426f63 803                                                                                                                      bdca0 00000020
[   41.656449]    803e8d68 83875914 80420000 800a4800 82d18c54 800a6834 803c32dc                                                                                                                       80420000
[   41.656449]    00000003 83875914 80420000 80094b08 82d18c54 8387594c 00000000                                                                                                                       0000003e
[   41.656449]    00000001 00000000 83293d58 83a54f00 83a54800 70687930 00000000                                                                                                                       00000000
[   41.656449]    00000000 00000000 00000000 00000000 00000000 00000000 00000000                                                                                                                       00000000
[   41.656449]    ...
[   41.656626] Call Trace:
[   41.656699] [<800a6834>] vprintk_default+0x24/0x30
[   41.656736] [<800a4800>] printk+0x2c/0x38
[   41.656760] [<800a6834>] vprintk_default+0x24/0x30
[   41.656813] [<80094b08>] print_worker_info+0x148/0x174
[   41.656952] [<83293d58>] ieee80211_ibss_leave+0xb90/0x1900 [mac80211]
[   41.657014] [<80081628>] warn_slowpath_common+0xa0/0xd0
[   41.657057] [<801a3ff0>] dump_stack+0x14/0x28
[   41.657085] [<80071a24>] show_stack+0x50/0x84
[   41.657108] [<80081628>] warn_slowpath_common+0xa0/0xd0
[   41.657158] [<83364c60>] ath9k_calculate_summary_state+0x250/0x60c [ath9k]
[   41.657217] [<800816dc>] warn_slowpath_null+0x18/0x24
[   41.657292] [<83364c60>] ath9k_calculate_summary_state+0x250/0x60c [ath9k]
[   41.657391] [<83365418>] ath9k_set_txpower+0x148/0x498 [ath9k]
[   41.657566] [<832d2c74>] cleanup_module+0xa74/0xd4c [mac80211]
[   41.657611] [<800a3ed8>] print_time+0xa8/0xb8
[   41.657687] [<800a6684>] vprintk_emit+0x404/0x43c
[   41.657850] [<832b9dc8>] ieee80211_sta_rx_notify+0x258/0x32c [mac80211]
[   41.658068] [<832ba6b4>] ieee80211_sta_rx_queued_mgmt+0x63c/0x734 [mac80211]
[   41.658201] [<832aa4ac>] ieee80211_tx_prepare_skb+0x210/0x230 [mac80211]
[   41.658399] [<800af608>] mod_timer+0x15c/0x190
[   41.658559] [<832ba8c8>] ieee80211_sta_work+0xfc/0xe1c [mac80211]
[   41.658730] [<832940b4>] ieee80211_ibss_leave+0xeec/0x1900 [mac80211]
[   41.658796] [<8009eca0>] dequeue_task_fair+0x44/0x130
[   41.658890] [<80092a5c>] process_one_work+0x1f8/0x334
[   41.658983] [<80093858>] worker_thread+0x2b4/0x408
[   41.659022] [<800935a4>] worker_thread+0x0/0x408
[   41.659061] [<800935a4>] worker_thread+0x0/0x408
[   41.659091] [<80097b90>] kthread+0xdc/0xe8
[   41.659179] [<80097ab4>] kthread+0x0/0xe8
[   41.659218] [<80060878>] ret_from_kernel_thread+0x14/0x1c
[   41.659254]
[   41.659272] ---[ end trace 920e3d56246b0d42 ]---
[   41.659306] ------------[ cut here ]------------
[   41.659364] WARNING: CPU: 0 PID: 32 at compat-wireless-2016-06-20/drivers/net                                                                                                                      /wireless/ath/ath9k/beacon.c:642 ath9k_calculate_summary_state+0x250/0x60c [ath9                                                                                                                      k]()
[   41.659379] Modules linked in: ath9k ath9k_common pppoe ppp_async iptable_nat                                                                                                                       ath9k_hw ath pppox ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4                                                                                                                       mac80211 ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_state xt_nat xt                                                                                                                      _multiport xt_mark xt_mac xt_limit xt_id xt_conntrack xt_comment xt_TCPMSS xt_RE                                                                                                                      DIRECT xt_LOG xt_CT slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 n                                                                                                                      f_nat nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_ra                                                                                                                      w iptable_mangle iptable_filter ip_tables crc_ccitt compat ledtrig_usbdev ip6t_R                                                                                                                      EJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_raw ip6table_mangle ip6t                                                                                                                      able_filter ip6_tables x_tables ohci_platform ohci_hcd ehci_platform ehci_hcd gp                                                                                                                      io_button_hotplug usbcore nls_base usb_common
[   41.659666] CPU: 0 PID: 32 Comm: kworker/u2:2 Tainted: G        W       4.4.1                                                                                                                      4 #1
[   41.659820] Workqueue: phy0 ieee80211_ibss_leave [mac80211]
[   41.659832] Stack : 83bc498c 83358b20 82d18c54 800a6834 838b1180 80426f63 803                                                                                                                      bdca0 00000020
[   41.659832]    803e8d68 83875914 80420000 800a4800 82d18c54 800a6834 803c32dc                                                                                                                       80420000
[   41.659832]    00000003 83875914 80420000 80094b08 82d18c54 8387594c 00000000                                                                                                                       0000003e
[   41.659832]    00000000 00000000 83293d58 83a54f00 83a54800 70687930 00000000                                                                                                                       00000000
[   41.659832]    00000000 00000000 00000000 00000000 00000000 00000000 00000000                                                                                                                       00000000
[   41.659832]    ...
[   41.660009] Call Trace:
[   41.660066] [<800a6834>] vprintk_default+0x24/0x30
[   41.660103] [<800a4800>] printk+0x2c/0x38
[   41.660127] [<800a6834>] vprintk_default+0x24/0x30
[   41.660180] [<80094b08>] print_worker_info+0x148/0x174
[   41.660313] [<83293d58>] ieee80211_ibss_leave+0xb90/0x1900 [mac80211]
[   41.660375] [<80081628>] warn_slowpath_common+0xa0/0xd0
[   41.660417] [<801a3ff0>] dump_stack+0x14/0x28
[   41.660445] [<80071a24>] show_stack+0x50/0x84
[   41.660468] [<80081628>] warn_slowpath_common+0xa0/0xd0
[   41.660519] [<83364c60>] ath9k_calculate_summary_state+0x250/0x60c [ath9k]
[   41.660578] [<800816dc>] warn_slowpath_null+0x18/0x24
[   41.660654] [<83364c60>] ath9k_calculate_summary_state+0x250/0x60c [ath9k]
[   41.660753] [<8336546c>] ath9k_set_txpower+0x19c/0x498 [ath9k]
[   41.660926] [<832d2c74>] cleanup_module+0xa74/0xd4c [mac80211]
[   41.660975] [<800a3ed8>] print_time+0xa8/0xb8
[   41.661051] [<800a6684>] vprintk_emit+0x404/0x43c
[   41.661215] [<832b9dc8>] ieee80211_sta_rx_notify+0x258/0x32c [mac80211]
[   41.661432] [<832ba6b4>] ieee80211_sta_rx_queued_mgmt+0x63c/0x734 [mac80211]
[   41.661566] [<832aa4ac>] ieee80211_tx_prepare_skb+0x210/0x230 [mac80211]
[   41.661664] [<800af608>] mod_timer+0x15c/0x190
[   41.661804] [<832ba8c8>] ieee80211_sta_work+0xfc/0xe1c [mac80211]
[   41.661975] [<832940b4>] ieee80211_ibss_leave+0xeec/0x1900 [mac80211]
[   41.662040] [<8009eca0>] dequeue_task_fair+0x44/0x130
[   41.662133] [<80092a5c>] process_one_work+0x1f8/0x334
[   41.662226] [<80093858>] worker_thread+0x2b4/0x408
[   41.662264] [<800935a4>] worker_thread+0x0/0x408
[   41.662304] [<800935a4>] worker_thread+0x0/0x408
[   41.662333] [<80097b90>] kthread+0xdc/0xe8
[   41.662421] [<80097ab4>] kthread+0x0/0xe8
[   41.662460] [<80060878>] ret_from_kernel_thread+0x14/0x1c
[   41.662496]
[   41.662512] ---[ end trace 920e3d56246b0d43 ]---
[   41.662570] wlan0: associated
[   41.663681] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   41.712508] ------------[ cut here ]------------
[   41.712609] WARNING: CPU: 0 PID: 1223 at compat-wireless-2016-06-20/drivers/n                                                                                                                      et/wireless/ath/ath9k/recv.c:559 ath_rx_tasklet+0xa20/0xc84 [ath9k]()
[   41.712626] Modules linked in: ath9k ath9k_common pppoe ppp_async iptable_nat                                                                                                                       ath9k_hw ath pppox ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4                                                                                                                       mac80211 ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_state xt_nat xt                                                                                                                      _multiport xt_mark xt_mac xt_limit xt_id xt_conntrack xt_comment xt_TCPMSS xt_RE                                                                                                                      DIRECT xt_LOG xt_CT slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 n                                                                                                                      f_nat nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_ra                                                                                                                      w iptable_mangle iptable_filter ip_tables crc_ccitt compat ledtrig_usbdev ip6t_R                                                                                                                      EJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_raw ip6table_mangle ip6t                                                                                                                      able_filter ip6_tables x_tables ohci_platform ohci_hcd ehci_platform ehci_hcd gp                                                                                                                      io_button_hotplug usbcore nls_base usb_common
[   41.712933] CPU: 0 PID: 1223 Comm: dhcp.sh Tainted: G        W       4.4.14 #                                                                                                                      1
[   41.712949] Stack : 803dc5a4 00000000 00000000 80430000 8398f980 80426f63 803                                                                                                                      bdca0 000004c7
[   41.712949]    80493790 83370000 00000001 83181798 02d8bfa0 800a6834 803c32dc                                                                                                                       80420000
[   41.712949]    00000003 83370000 803c16e8 82d2bb0c 02d8bfa0 800a4800 012c972b                                                                                                                       00000000
[   41.712949]    00000000 00000000 00000000 00000000 00000000 00000000 00000000                                                                                                                       00000000
[   41.712949]    00000000 00000000 00000000 00000000 00000000 00000000 00000000                                                                                                                       00000000
[   41.712949]    ...
[   41.713121] Call Trace:
[   41.713181] [<83370000>] ath9k_dfs_process_phyerr+0x1728/0x307c [ath9k]
[   41.713233] [<800a6834>] vprintk_default+0x24/0x30
[   41.713270] [<83370000>] ath9k_dfs_process_phyerr+0x1728/0x307c [ath9k]
[   41.713294] [<800a4800>] printk+0x2c/0x38
[   41.713328] [<80081628>] warn_slowpath_common+0xa0/0xd0
[   41.713378] [<801a3ff0>] dump_stack+0x14/0x28
[   41.713409] [<80071a24>] show_stack+0x50/0x84
[   41.713432] [<80081628>] warn_slowpath_common+0xa0/0xd0
[   41.713467] [<8336714c>] ath_rx_tasklet+0xa20/0xc84 [ath9k]
[   41.713527] [<800816dc>] warn_slowpath_null+0x18/0x24
[   41.713594] [<8336714c>] ath_rx_tasklet+0xa20/0xc84 [ath9k]
[   41.713669] [<833647c8>] ath9k_tasklet+0x1ac/0x230 [ath9k]
[   41.713700] [<800a7c10>] handle_irq_event_percpu+0x154/0x188
[   41.713732] [<8008415c>] tasklet_action+0x80/0xc8
[   41.713757] [<80083a84>] __do_softirq+0x164/0x290
[   41.713794] [<800aaf68>] handle_percpu_irq+0x50/0x80
[   41.713843] [<8006a678>] plat_irq_dispatch+0xbc/0xf4
[   41.713880] [<80060830>] ret_from_irq+0x0/0x4
[   41.713912] [<8007d160>] r4k_flush_data_cache_page+0x30/0x3c
[   41.713960] [<8007c638>] r4k_blast_dcache_page_dc32+0x38/0x9c
[   41.714007] [<800efa8c>] handle_mm_fault+0x240/0xb78
[   41.714056] [<8007663c>] __do_page_fault+0x134/0x474
[   41.714089] [<800f21b8>] get_unmapped_area+0x50/0xa4
[   41.714114] [<800f4204>] do_brk+0x17c/0x290
[   41.714156] [<801054c8>] vfs_read+0xf8/0x11c
[   41.714180] [<800f444c>] SyS_brk+0x134/0x174
[   41.714204] [<80060820>] ret_from_exception+0x0/0x10
[   41.714243] [<80062bac>] sys_call_table+0xb4/0x5a8
[   41.714263]
[   41.714280] ---[ end trace 920e3d56246b0d44 ]---
[   42.138303] br-lan: port 1(eth0) entered forwarding state

**Comment by nbd168** [comment]
Please post your /etc/config/wireless

**Comment by tomudo** [comment]
This is my /etc/config/wireless .

config wifi-device 'radio0'
        option type 'mac80211'
        option channel 'auto'
        option hwmode '11g'
        option path 'platform/ar933x_wmac'
        option htmode 'HT20'
        option txpower '18'
        option country 'US'
        option dtim_period '2'
        option frag '2306'
        option rts '2307'
        option distance '500'
        option disabled '0'

config wifi-iface
        option device 'radio0'
        option mode 'sta'
        option network 'wwan'
        option disassoc_low_ack '0'
        option disabled '0'
        option ssid 'MyWAN'
        option encryption 'psk2'
        option key '12345678'
        option macaddr '00:11:22:33:44:55'

config wifi-iface
        option device 'radio0'
        option mode 'ap'
        option ssid 'MyAP'
        option disassoc_low_ack '0'
        option encryption 'psk'
        option key '12345678'
        option network 'lan'
        option disabled '0'

**Comment by lsiudut** [comment]
+1, I observe same warnings on WDR4300 with only 5Ghz radio enabled in client mode. As mentioned though, these seems to be warnings only. Radio works well (at least for now, ~30 minutes of constant rate transfer).

**Comment by psyke83** [comment]
I don't think it's isolated to 5Ghz, as I'm having the same problem here on TL-WR842ND running in STA mode (set up as a pseudobridge).

Wireless is unstable in STA mode, but I don't think it's related to whatever issue is causing these kernel warnings. OpenWrt 15.05.1 has the same flaky connection, and I've managed to solve it either by disabling AMPDU on the AP or patching the ath9k driver on the client router to disable AMPDU support.

```
config wifi-device 'radio0'
        option type 'mac80211'
        option hwmode '11g'
        option path 'pci0000:00/0000:00:00.0'
        option htmode 'HT20'
        option country 'IE'
        option frag '2346'
        option rts '2347'
        option disabled '0'
        option channel '13'
        option txpower '20'

config wifi-iface
        option network 'wwan'
        option ssid 'my_ssid'
        option encryption 'psk2'
        option device 'radio0'
        option mode 'sta'
        option bssid 'my_mac'
        option key 'my_pass'
```

**Comment by nbd168** [comment]
Fixed in r1115
