### ISSUE TITLE
Missing bcm5720 ethernet chipset support

### ISSUE THREAD

**Issue by amaumene** [lede-project/source#206]
Hi,

I'd like to use lede on my HP Microserver Gen8 but I'm missing the ethernet driver (annoying for a router).

Would it be possible to add it ?

Thanks in advance.

**Comment by jow-** [comment]
What is a 2HP Microserver Gen8" and which ethernet driver is missing for it?

**Comment by amaumene** [comment]
Hi,

This is "HP Microserver Gen8": http://www8.hp.com/sg/en/products/proliant-servers/product-detail.html?oid=5379860

Anyway I had to install the tg3 for this broadcom ethernet card. I'm sorry for the noise I'm just not familiar with these chispet.

Sorry for the noise but thanks for this quick answer :)
