### ISSUE TITLE
Build is building all Marvell targets.

### ISSUE THREAD

**Issue by northbound1** [lede-project/source#216]
The first time I can understand there were changes. But in the make menuconfig I untagged all except WRT1900AC (Mamba) In target profile. 
It still builds everything Marvell. Is there something else I am missing?
I did do a make clean.
git pull 
./scripts/feeds update -a 
./scripts/feeds install -a 
make defconfig
Thanks.

**Comment by nbd168** [comment]
Fixed in r1117

**Comment by thagabe** [comment]
Like @nbd168 said just do a git pull again and it should be all patched up! I'm building just the selected target now
