### ISSUE TITLE
WNDR4700 (APM821xx) - Do not operate the automatic lighting or LED goes off (depending on the relevant operations of connecting / disconnecting the device) for hard drive and USB devices.

### ISSUE THREAD

**Issue by build000** [lede-project/source#222]
As the topic:
1). no trigger (/sys) "disk" or "sda", or another name to hard disk
2).  trigger usb devices there but the LED does not light up

**Comment by thess** [comment]
Issue moved to [FS#149](https://bugs.lede-project.org/index.php?do=details&task_id=149)
