### ISSUE TITLE
batman-adv not working

### ISSUE THREAD

**Issue by chaosenze** [lede-project/source#228]
On lede router:
```
> lsmod|grep batman
batman_adv            127531  0
crc16                   1031  1 batman_adv
libcrc32c                663  1 batman_adv
```
```
> batctl -v
batctl 2016.2 [batman-adv: module not loaded]
```
 Module is loaded but batctl don't find it.. and the routing don't working.
```
iw mesh0 mpath dump
DEST ADDR         NEXT HOP          IFACE       SN      METRIC  QLEN    EXPTIME         DTIM    DRET    FLAGS
04:f0:21:14:c9:42 00:00:00:00:00:00 mesh0       0       0       0       0       1600    4       0x0
00:23:eb:2c:fc:45 00:00:00:00:00:00 mesh0       0       0       4       0       800     3       0x2
```

On the other site I have an Arch linux with batman-adv
```
> batctl -v
batctl 2016.2 [batman-adv: 2016.1]
```
```
>iw mesh0 mpath dump
DEST ADDR         NEXT HOP          IFACE       SN      METRIC  QLEN    EXPTIME         DTIM    DRET    FLAGS
00:23:eb:2c:11:44 00:00:00:00:00:00 mesh0       0       0       6       0       1600    4       0x6
04:f0:21:14:c9:42 04:f0:21:14:c9:42 mesh0       11460   4097    0       4420    0       0       0x15
```
this are 2 meshpoint's, the first one is the batman point with lede.

**Comment by NeoRaider** [comment]
Hi,
the "module not loaded" is just a cosmetic issue; I've opened a PR that fixes it: https://github.com/openwrt-routing/packages/pull/221

You seem to be using batman-adv over 11s mesh interfaces (which is generally okay if you disable 11s forwarding). Have you checked if the 11s interface is working without batman-adv?

If 11s is working, and only batman-adv fails, this is the wrong place to report it; this repo is for the LEDE core only, which batman-adv isn't part of. You should directly contact the batman-adv developers (e.g. in IRC or on their ML) or maybe open an issue in the https://github.com/openwrt-routing/packages repo in that case.

If it is indeed an 11s issue, we need more information: What WLAN cards/drivers are you using? How are they configured?

**Comment by thess** [comment]
Issue moved to [FS#150](https://bugs.lede-project.org/index.php?do=details&task_id=150)
