### ISSUE TITLE
Packages do not have NEON support

### ISSUE THREAD

**Issue by 4mig4** [lede-project/source#248]
NEON support is not enabled for any of the packages so ARM A9 platforms such as clearfog pro a1 in particular are not taking advantage of accelerated crypto hashs or mem* functions

**Comment by wongsyrone** [comment]
> NEON is included in all Cortex-A8 devices but is optional in Cortex-A9 devices.

You'd better adjust settings yourself.

**Comment by 4mig4** [comment]
There you go , this concerns the Solidrun Clearfog Pro A1

**Comment by nbd168** [comment]
It seems to me that not all Armada SoC types have neon support, so we can't enable it globally for the target. For crypto, it might be possible to enable neon support in the kernel config without breaking older SoC types.

**Comment by 4mig4** [comment]
How about including it for the clearfog target ? Do we have an override per target for packages ?

**Comment by nbd168** [comment]
Crypto and hash functions enabled in r1467. For packages a separate subtarget is needed
