### ISSUE TITLE
sysntp does not resolves IPv6 when IPv6 only stack

### ISSUE THREAD

**Issue by 4mig4** [lede-project/source#249]
sysntp (busybox ntp) does not resolve IPv6 addresses when the machine is IPv6 stack based only.

proposed solution exist:

https://dev.openwrt.org/attachment/ticket/12167/0001-busybox-make-ntpd-prefer-IPv6-addresses.patch

http://lists.busybox.net/pipermail/busybox/2016-August/084529.html

**Comment by blogic** [comment]
duplicate of FS#84
