### ISSUE TITLE
mksquashfs4 can't append to an existing filesystem

### ISSUE THREAD

**Issue by teknoraver** [lede-project/source#251]
It seems this patch https://github.com/lede-project/source/blob/master/tools/squashfs4/patches/160-expose_lzma_xz_options.patch
breaks append to an existing filesystem when using xz and a bcj filter.
It can be reproduced with:

```bash
opts='-comp xz -Xbcj x86 -processors 1'

mkdir root1 root2
echo 12345678 >root1/file1
echo 87654321 >root2/file2

staging_dir/host/bin/mksquashfs4 root1 out.img -noappend $opts
staging_dir/host/bin/mksquashfs4 root2 out.img $opts
```

**Comment by blogic** [comment]
@KanjiMonster was this one of your patches ?

**Comment by blogic** [comment]
@teknoraver chances of this getting looked at are near 0
