### ISSUE TITLE
 Add mptcp protocol support

### ISSUE THREAD

**Issue by qiuzi** [lede-project/source#253]
Please join the patch to the latest kernel

[Uploading mptcp-v4.1.25-6d0ba0f70770.txt…]()

**Comment by blogic** [comment]
the link links to itself. if you want the patch added, then please send a PR

**Comment by qiuzi** [comment]
[http://multipath-tcp.org/patches/mptcp-v4.1.25-6d0ba0f70770.patch](url)

**Comment by nbd168** [comment]
The patch is way too big, only covers one kernel version and touches *lots* of unrelated pieces of code. We will not merge it that way.

**Comment by debiansid** [comment]
Ovh released the code
