### ISSUE TITLE
block-mount: unable to establish ubus connection via LuCI interface

### ISSUE THREAD

**Issue by pcmoore** [lede-project/source#283]
On a recent install of LEDE whenever I try to "Save & Apply" on the "System" -> "Mount Points" LuCI configuration page I see the following errors at the top of the page and the system appears to wedge itself:

    /usr/lib/lua/luci/util.lua:623: Unable to establish ubus connection stack traceback: [C]: in function 'assert'
    /usr/lib/lua/luci/util.lua:623: in function 'ubus'
    /usr/lib/lua/luci/dispatcher.lua:347: in function 'dispatch' 
    /usr/lib/lua/luci/dispatcher.lua:141: in function {output cutoff}

Attempting to access any other LuCI pages results in the following plaintext output in my browser:

    /usr/lib/lua/luci/util.lua:623: Unable to establish ubus connection
    stack traceback:
    	[C]: in function 'assert'
    	/usr/lib/lua/luci/util.lua:623: in function 'ubus'
    	/usr/lib/lua/luci/dispatcher.lua:347: in function 'dispatch'
    	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>

The system needs to be rebooted to restore functionality.  The version string at the bottom of the LuCI pages is below:

    LuCI Master (git-16.232.29304-c0af360) / LEDE Reboot r1377

If you need any additional information please let me know, I'm happy to help debug the situation as needed.

**Comment by pcmoore** [comment]
Additional version information in case it is helpful:

    # opkg list | grep block-mount
    block-mount - 2016-07-24-addd7dc21fe99f2701c1d4708071578052af401d

    # opkg list | grep ubus
    libubus - 2016-07-02-053be7df871e05478284235732f8b0608089512f
    libubus-lua - 2016-07-02-053be7df871e05478284235732f8b0608089512f
    ubus - 2016-07-02-053be7df871e05478284235732f8b0608089512f
    ubusd - 2016-07-02-053be7df871e05478284235732f8b0608089512f
    uhttpd-mod-ubus - 2016-06-16-9d9f07142bbef1c63a79620967a847a9493105e5

    # opkg list | grep rpc
    rpcd - 2016-06-30-23417e94d25570e6d62542bac46edd51e8e0243a
    rpcd-mod-file - 2016-06-30-23417e94d25570e6d62542bac46edd51e8e0243a
    rpcd-mod-iwinfo - 2016-06-30-23417e94d25570e6d62542bac46edd51e8e0243a
    rpcd-mod-rpcsys - 2016-06-30-23417e94d25570e6d62542bac46edd51e8e0243a

**Comment by jow-** [comment]
Seems `rpcd` or `ubusd` are dying as a consequence of the mount call. Did you remount internal directories like `/var` or `/tmp` ? What is your fstab config? What is in `logread` after such an error?

**Comment by pcmoore** [comment]
Unfortunately I will not have access to the system until next week, this weekend at the earliest; I'll get that information then and update this issue.

**Comment by blogic** [comment]
i have just tested this in lots of combos and even tried mad stuff like mounting the usb media under / /tmp /var ... and it just worked.

**Comment by pcmoore** [comment]
> Did you remount internal directories like /var or /tmp ?

Not that I am aware of, although I first noticed this by clicking on the "Generate Config" option at the top of the LuCI interface and then clicking "Save & Apply".  Perhaps the default generated config did something odd?

I never tried to "Save & Apply" before selecting "Generate Config".  Anytime I bring up the page now and select "Save & Apply" without selecting anything else I see the error.

> What is your fstab config?

It appears empty:

    # cat /etc/fstab 
    # <file system> <mount point> <type> <options> <dump> <pass>
    #

I also took a screenshot of the LuCI page and placed a copy at the URL below:

* http://www.paul-moore.com/drop/lede/luci_screenshot-1.png

> What is in logread after such an error?

The logread command appears to fail after the error

    # logread
    Failed to connect to ubus

**Comment by pcmoore** [comment]
I see the "response_needed" label is still attached to this issue, do you need anything else from me?

**Comment by jow-** [comment]
Seems like your ubus daemon is crashing - maybe you do not have enough ram on your device?

**Comment by pcmoore** [comment]
The device has 1G of memory, which should be plenty, and the idle memory footprint seems to agree:

    # free
                 total       used       free     shared    buffers     cached
    Mem:        951828      40312     911516       1040       1020      13088
    -/+ buffers/cache:      26204     925624
    Swap:            0          0          0

I did notice one thing just now while testing this failure again, it appears that /proc gets unmounted and never remounted; /sys and /dev appear to have similar problems.

Before the failure:

    # mount                                                            
    /dev/mmcblk0p2 on / type ext4 (rw,noatime,block_validity,delalloc,barrier,user_xattr)                                                                           
    proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)                        
    sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)                       
    tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noatime)                              
    /dev/mmcblk0p1 on /boot type vfat (rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,error =remount-ro)                         
    tmpfs on /dev type tmpfs (rw,nosuid,relatime,size=512k,mode=755)                
    devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,mode=600)             
    debugfs on /sys/kernel/debug type debugfs (rw,noatime)

... and after the failure:

    # mount                                                            
    mount: failed to read mtab: No such file or directory                           
    # ls -l /proc/mtab
    ls: /proc/mtab: No such file or directory
    # ls -l /proc
    # ls -l /sys
    # ls -l /dev
    -rw-r--r--    1 root     root             0 Sep 12 19:11 null

Hopefully that provides some insight?

**Comment by pcmoore** [comment]
FWIW, after the failure I seem unable to mount /proc and /sys manually:

    # mount -t proc proc /proc
    mount: wrong fs type, bad option, bad superblock on proc,
           missing codepage or helper program, or other error
    
           In some cases useful info is found in syslog - try
           dmesg | tail or so.
    # mount -t sysfs sys /sys
    mount: wrong fs type, bad option, bad superblock on sys,
           missing codepage or helper program, or other error
    
           In some cases useful info is found in syslog - try
           dmesg | tail or so.

... only rebooting the system seems to work.

**Comment by thess** [comment]
@jow-  FYI

@pcmoore - If this problem still persists in that latest builds, please enter an issue on our bug reporting system at https://bugs.lede-project.org. I am closing this for now since we will be no longer using Github for bug reports/issues here.

Sorry for any inconvenience...
