### ISSUE TITLE
luci-app-statistics: no support for collectd-mod-thermal

### ISSUE THREAD

**Issue by pcmoore** [lede-project/source#285]
On a recent install of LEDE there does not appear to be any graphical/LuCI support for the collectd-mod-thermal plugin.

The relevant package version information:

    # opkg list | grep '^luci-app-statistics'
    luci-app-statistics - git-16.232.29304-c0af360-1 - LuCI Statistics Application
    # opkg list | grep collectd-mod-thermal
    collectd-mod-thermal - 5.5.2-1 - system temperatures input plugin

The version string at the bottom of the LuCI pages is below:

    LuCI Master (git-16.232.29304-c0af360) / LEDE Reboot r1377

If you need any additional information please let me know.

**Comment by jow-** [comment]
I need some example rrd files and the file directory hierarchy to implement thermal plugin support.

**Comment by pcmoore** [comment]
Unfortunately I will not have access to the system until next week, possibly this weekend.  I can grab a copy of the thermal plugin *.rrd file(s) as well as a file directory layout, but can you be a bit more specific about which fs hierarchy?  For example, would a 'ls -lR /tmp/rrd*' work?

**Comment by jow-** [comment]
Yep, that would work. I just need to see how collectd lays out the data in order to define an appropriate LuCI data model.

**Comment by pcmoore** [comment]
Sorry for the delay, here is the file directory layout:

    # ls -lR /tmp/rrd/*/thermal-thermal_zone0/
    /tmp/rrd/tmwnet/thermal-thermal_zone0/:
    -rw-r--r--    1 root     root          5440 Aug 28 22:09 temperature.rrd

... it was generated with the following file:

    # cat /etc/collectd/conf.d/thermal.conf 
    LoadPlugin "thermal"
    <Plugin "thermal">
            Device "thermal_zone0"
            IgnoreSelected false
    </Plugin>

The temperature.rrd file can be found at the link below:

* http://www.paul-moore.com/drop/lede/temperature.rrd

... let me know if you need any more information.

**Comment by pcmoore** [comment]
I see the "response_needed" label is still attached to this issue, do you need anything else from me?

**Comment by thess** [comment]
@jow-  FYI

@pcmoore - If this problem still persists in that latest builds, please enter an issue on our bug reporting system at https://bugs.lede-project.org. I am closing this for now since we will be no longer using Github for bug reports/issues here.

Sorry for any inconvenience...
