### ISSUE TITLE
apm82181 wndr4700 compile glibc error

### ISSUE THREAD

**Issue by xixijojo** [lede-project/source#286]
rtld.c: In function 'dl_main':
rtld.c:2176:1: error: section type conflict with __pointer_chk_guard_local
}
^
rtld.c:96:11: note: '__pointer_chk_guard_local' was declared here
uintptr_t __pointer_chk_guard_local
           ^
../o-iterator.mk:9: recipe for target '/home/johnin/lede/source/build_dir/toolchain-powerpc_464fp_gcc-5.4.0_glibc-2.22/glibc-2.22-b995d95-final/elf/rtld.os' failed

**Comment by chunkeey** [comment]
LEDE switched to glibc 2.24 with 4badb8a023bf187c235f1e558ab96c41729edbcb.
I was able to successfully compile the toolchain-powerpc_464fp_gcc-5.4.0_glibc-2.24 toolchain and produce an image for the WNDR4700. so, please update your sources and retry with 2.24.

**Comment by thess** [comment]
Issue move to [FS#144](https://bugs.lede-project.org/index.php?do=details&task_id=144)
