### ISSUE TITLE
wifi broken with ath9k: switch to using mac80211 intermediate software queues (fe7fdd3bb4bc44b6603fbde14cdc2ad55ef1f612)

### ISSUE THREAD

**Issue by dwayne80** [lede-project/source#287]
wifi connects and everything appears normal but the ap sometimes (often) wont pass any wifi traffic, reverting this commit and rebuilding fixed the issue for me.

logs / iwinfo shows no problems. image is basic with very default configuration plus standard sqm filters.

router is tplink TL-WDR4300 (Atheros AR9344 rev 2).

**Comment by dwayne80** [comment]
stopping/disabling sqm also seems to have helped, i'll keep testing..

**Comment by dwayne80** [comment]
seems unrelated to sqm after more testing as problems continue even when removing sqm-scripts from the image. wifi works intermittently.. no logs/errors what so ever to report though..

**Comment by dwayne80** [comment]
it seems wifi will run fine for a while after 'wifi up', and after that a lot of traffic just seems to end up in a black hole.

**Comment by Panja0** [comment]
Having a (sort of) same problem here on an Archer C7. 
2.4GHz connection with a Windows clients keeps dropping intermittently.

**Comment by Panja0** [comment]
I was running r1404 on the router (installed as dumb ap) and with this specific client I was running a ping to the Google public DNS server (8.8.8.8). After 20 minutes of ping test I had 67% packet loss. I re-installed the stock firmware on the router, set it up as dumb ap and tried the exact same ping test. After 30 minutes 0% packet loss...

**Comment by Panja0** [comment]
Just tried r1432, same problem...

**Comment by Panja0** [comment]
Ok, did some further testing.
My problem seems to be related to "power" consumption. Underneath I'll try to explain.

This is the situation:
Archer C7 flashed with r1432 --> Windows 10 (x64) laptop connected to the 2.4GHz radio and running on battery = a lot packet loss (70ish %) when pinging to 8.8.8.8

Archer C7 flashed with r1432 --> Windows 10 (x64) laptop connected to the 2.4GHz radio and running on external power = NO packet loss when pinging to 8.8.8.8

Archer C7 flashed with stock firmware --> Windows 10 (x64) laptop connected to the 2.4GHz radio and running on battery = NO packet loss when pinging to 8.8.8.8

Archer C7 flashed with stock firmware --> Windows 10 (x64) laptop connected to the 2.4GHz radio and running on external power = NO packet loss when pinging to 8.8.8.8

**Comment by Panja0** [comment]
Just tested r1442.
Same problem for me...

**Comment by nbd168** [comment]
Does the issue disappear if you delete package/kernel/mac80211/patches/337-ath9k-Switch-to-using-mac80211-intermediate-software.patch?

**Comment by Panja0** [comment]
How can I delete that package? I can't find it in my package list.

**Comment by Panja0** [comment]
nbd, I installed the build with "337-ath9k-Switch-to-using-mac80211-intermediate-software.patch" removed. It's a lot better but not fixed completely for me. Still having some packet loss. But instead of the 60 - 70% packet loss in 20 minutes it around 3 - 5%.

**Comment by ignisf** [comment]
@Panja0 does setting `option uapsd 0` in the BSS configuration have any effect?

**Comment by Panja0** [comment]
Seems to be better!
Though still some packet loss. But with "option uapsd 0" added to my config it's very minimal.
1 packet lost per 350 - 400 packets.

**Comment by nbd168** [comment]
How about if you use `option uapsd 0` with the 337 patch included?

**Comment by dwayne80** [comment]
following irc logs and posts here i believe me and Panja0 are not experiencing the same issue.

to update my own issue, ap is running great and without issues as long as the commit in title is reverted.

apologies for not being more available for troubleshooting and pinpointing this issue, i have a hectic schedule.

**Comment by Panja0** [comment]
Dwayne, sorry for hi-jacking your topic!

@nbd:
I will give it a try tomorrow. Let you know!

**Comment by Panja0** [comment]
Nope, I have flashed the latest (generic) build r1444 and put: `option uapsd '0'` in to my wireless config. Same problem.

**Comment by nbd168** [comment]
Please try the latest version from my staging branch, or the images at http://nbd.name/ar71xx-test/

**Comment by Panja0** [comment]
Thanks for the update.
At the moment I'm not able to install this.
When I have some more time I will be testing it. Cheers

**Comment by gregecslo** [comment]
Hello!
I tried it and it`s even worse. I was able to do 2-3 speedtests now I can only finish 1 and then wifi goes offline.

**Comment by nbd168** [comment]
Updated my staging tree and the images. Please test again.

**Comment by gregecslo** [comment]
Hi!

Will do it this afternoon :)

**Comment by nbd168** [comment]
The github issue tracker will be closed soon-ish. If the current version does not work, please create an issue on https://bugs.lede-project.org

**Comment by gregecslo** [comment]
https://bugs.lede-project.org/index.php?do=details&task_id=34
Already there 2 moths ago :)
It`s very same issue.

**Comment by nbd168** [comment]
That issue might be something else. Did you verify that your issue is gone if you remove the patch mentioned in this thread?

**Comment by gregecslo** [comment]
nope, but I tested latest build you posted and same result... Wifi just drops under medium load...

**Comment by nbd168** [comment]
Okay, then I'm going to assume that your issue is a different one than what was reported here by @dwayne80. What hardware are you using?

**Comment by gregecslo** [comment]
Hi.
Wrt160 nl...
But it's similar issue, can you revert the patch, I can try it.

**Comment by Panja0** [comment]
@nbd

Probably I have some time tomorrow to test. 
Which version so I need to take? 

Cheers
Panja

**Comment by Panja0** [comment]
@nbd168 I have tried the latest build from your tree and it's even worse.

**Comment by gregecslo** [comment]
I`m telling you it`s the same issue, or at least tight connected one.

**Comment by Panja0** [comment]
My problem seems to be gone after some extensive testing together with @nbd168 .
As far as I know the fix will be implemented in the master image later this weekend?

**Comment by gregecslo** [comment]
what was the culprit?

**Comment by Panja0** [comment]
I think it had to do something with the patch "ath9k: switch to using mac80211 intermediate software queues". But probably @nbd168 can tell you more about it. :)

**Comment by gregecslo** [comment]
Cool, if nbd can build new one i will test it right away!

**Comment by tohojo** [comment]
This was the fix: https://git.lede-project.org/?p=source.git;a=commit;h=dbc9ee5b722f3a8a359bdbd20b11c5a0239cb0b3

**Comment by Panja0** [comment]
That's the one indeed! 👍 
When can we expect it in the master image?

**Comment by gregecslo** [comment]
Currently it is waiting for buildbot to start si I guess today ;)

**Comment by Panja0** [comment]
Wicked!

**Comment by gregecslo** [comment]
It is just started to build.
Eta 40 mins...

**Comment by gregecslo** [comment]
Unfortunatley it didn't fixed my issue, so nbd was correct and issue on lede bugtracker is not connected to this one. However after I flashed this I could do 5 speedtests in a row which was impossible with previous builds...

**Comment by nbd168** [comment]
Fix committed in r1491

**Comment by fbernier** [comment]
Issue also not fixed here just like gregecslo. Guess we should open a new one?
