### ISSUE TITLE
KCONFIG options in package makefiles do not influence the kernel config

### ISSUE THREAD

**Issue by RoadRunnr** [lede-project/source#289]
for example, package/kernel/linux/modules/netsupport.mk defines kmod_udptunnel4.

The expected behavior is that when .config contains CONFIG_PACKAGE_kmod-udptunnel4=y, that the needed kernel config options are set, the modules is build and included in the final image.

Nothing of the above happens, the kernel option never gets enabled.

**Comment by jow-** [comment]
The `kmod-udptunnel4` package is a hidden transient dependency which you cannot select directly. Instead you need to select something depending on it, e.g. `kmod-l2tp`.
