### ISSUE TITLE
ds-lite protocol does not learn AFTR gateway from DHCPv6

### ISSUE THREAD

**Issue by Schimmelreiter** [lede-project/source#293]
As one can see in
https://github.com/lede-project/source/blob/master/package/network/ipv6/ds-lite/files/dslite.sh#L21
the user has to supply an AFTR gateway in order for DS-lite to work.

However in real life scenarios the AFTR gateway is not part of the "login data" communicated to the customer, but it is sent according to this draft _Dynamic Host Configuration Protocol for IPv6 (DHCPv6) Option for Dual-Stack Lite_ as a DHCPv6 option:
https://tools.ietf.org/html/draft-ietf-softwire-ds-lite-tunnel-option-10

**Comment by jow-** [comment]
See https://github.com/lede-project/source/blob/master/package/network/ipv6/odhcp6c/files/dhcpv6.script#L157
