### ISSUE TITLE
Wireless Overview erroneous error re libiwinfo-lua package

### ISSUE THREAD

**Issue by wtogami** [lede-project/source#299]
```
Package libiwinfo required!
The libiwinfo-lua package is not installed. You must install this component for working wireless configuration!
```

`lede-ramips-rt3883-rt-n56u-squashfs-factory.bin    24-Aug-2016 18:47             3276804`

The `ibiwinfo-lua` package is installed and the latest version via opkg.

**Comment by mkresin** [comment]
Wrong bugtracker and duplicate of https://github.com/openwrt/luci/issues/780. You are the third person who reports this issue. And all reporters are using a rt3883 device. I guess we found a coherence.

**Comment by TeutonJon78** [comment]
I'm running into this problem on the C2600 build as well -- random package failures that often includes this package with the same symptom. This problem started sometime after r1382 (2016-8-19).

**Comment by thess** [comment]
Moved to [FS#136](https://bugs.lede-project.org/index.php?do=details&task_id=136)
