### ISSUE TITLE
sysupgrade broken on x86 generic?

### ISSUE THREAD

**Issue by debiansid** [lede-project/source#300]
`root@openwrt-x86:/tmp#`` `sysupgrade` `-n` `lede-x86-generic-combined-ext4.img.gz`
`Sending` `TERM` `to` `remaining` `processes` `...` `ubusd` `askfirst` `askfirst` `logd` `rpcd` `netifd` `odhcpd` `crond` `php-fpm` `uhttpd` `smbd` `nmbd` `unbound` `nginx` `ss-redir` `ss-tunnel` `vlmcsd` `ntpd` `aria2c` `dynamic_dns_upd` `dnsmasq`
`Sending` `KILL` `to` `remaining` `processes` `...` `askfirst` `askfirst`
`Switching` `to` `ramdisk...`
`Performing` `system` `upgrade...`
`Reading` `partition` `table` `from` `bootdisk...`
`Invalid` `partition` `table` `on` `/dev/sdb2`

`root@openwrt-x86:~#` `fdisk` `-l` `/dev/sdb`
`Disk` `/dev/sdb:` `7.5` `GiB,` `7994327040` `bytes,` `15613920` `sectors`
`Units:` `sectors` `of` `1` `*` `512` `=` `512` `bytes`
`Sector` size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xa0abacc1

Device     Boot   Start      End  Sectors  Size Id Type
/dev/sdb1  *        512     8703     8192    4M 83 Linux
/dev/sdb2          9216   533503   524288  256M 83 Linux
/dev/sdb3        534528  4728831  4194304    2G 82 Linux swap / Solaris
/dev/sdb4       4728832 15613919 10885088  5.2G 83 Linux

**Comment by debiansid** [comment]
I just tested on official openwrt x86-64 , sysupgrade is working

**Comment by thess** [comment]
Moved to [FS#135](https://bugs.lede-project.org/index.php?do=details&task_id=135)
