### ISSUE TITLE
Add support for multiple dnsmasq instances

### ISSUE THREAD

**Issue by kbabioch** [lede-project/source#301]
Currently dnsmasq can only be configured globally. There are situations where this is not good enough, especially if the goal is to isolate networks from each other. Running multiple dnsmasq instances bound only to specific interfaces solves this issue. This was already requested in the old OpenWRT bug tracker (see [here][1]), and patches were developed. Maybe this can finally be included into the mainline source, so people can take advantage of this.

[1]: https://dev.openwrt.org/ticket/8862

**Comment by thess** [comment]
Moved to [FS#132](https://bugs.lede-project.org/index.php?do=details&task_id=132)
