### ISSUE TITLE
Netgear r8000 cannot use 802.1x encryption

### ISSUE THREAD

**Issue by Halry** [lede-project/source#305]
My android phone can't connect to it.(tested on nexus 6p and samsung s7 edge)
Sun Aug 28 16:28:46 2016 daemon.debug hostapd: wlan2: STA 94:fe:22:11:22:33 IEEE 802.1X: Sending EAP Packet (identifier 247)
Sun Aug 28 16:28:46 2016 daemon.debug hostapd: wlan2: STA 94:fe:22:11:22:33 WPA: sending 1/4 msg of 4-Way Handshake
Sun Aug 28 16:28:46 2016 daemon.debug hostapd: wlan2: STA 94:fe:22:11:22:33 WPA: received EAPOL-Key frame (2/4 Pairwise)
Sun Aug 28 16:28:46 2016 daemon.debug hostapd: wlan2: STA 94:fe:22:11:22:33 WPA: sending 3/4 msg of 4-Way Handshake
Sun Aug 28 16:28:46 2016 daemon.info hostapd: wlan2: STA 94:fe:22:11:22:33 IEEE 802.11: disassociated
Sun Aug 28 16:28:46 2016 daemon.debug hostapd: wlan2: STA 94:fe:22:11:22:33 WPA: event 2 notification
Sun Aug 28 16:29:00 2016 daemon.info hostapd: wlan1: STA 94:fe:22:11:22:33 IEEE 802.11: associated
Sun Aug 28 16:29:00 2016 daemon.info hostapd: wlan1: STA 94:fe:22:11:22:33 IEEE 802.11: disassociated
Sun Aug 28 16:29:11 2016 daemon.info hostapd: wlan1: STA 94:fe:22:11:22:33 IEEE 802.11: associated
Sun Aug 28 16:29:11 2016 daemon.info hostapd: wlan1: STA 94:fe:22:11:22:33 IEEE 802.11: disassociated
 
However,Windows can connect to it.

Here are some my nexus 6p's dmesg:
CFG80211-ERROR wl_cfg80211_disconnect:Reason 17

**Comment by ignisf** [comment]
Could you please share your `/etc/config/wireless`?

**Comment by Halry** [comment]
`
config wifi-device 'radio0'
	option type 'mac80211'
	option channel '36'
	option hwmode '11a'
	option path '18000000.axi/bcma0:7/pci0000:00/0000:00:00.0/0000:01:00.0'
	option htmode 'VHT80'

config wifi-iface
	option device 'radio0'
	option network 'lan'
	option mode 'ap'
	option ssid 'OpenWrt'
	option encryption 'none'
	option disabled '1'

config wifi-device 'radio1'
	option type 'mac80211'
	option channel '11'
	option hwmode '11g'
	option path '18000000.axi/bcma0:8/pci0001:00/0001:00:00.0/0001:01:00.0/0001:02:01.0/0001:03:00.0'
	option htmode 'HT20'
	option disabled '1'

config wifi-iface
	option device 'radio1'
	option network 'lan'
	option mode 'ap'
	option ssid 'OpenWrt'
	option encryption 'none'

config wifi-device 'radio2'
	option type 'mac80211'
	option hwmode '11a'
	option path '18000000.axi/bcma0:8/pci0001:00/0001:00:00.0/0001:01:00.0/0001:02:02.0/0001:04:00.0'
	option htmode 'VHT80'
	option channel '153'
	option txpower '20'
	option country '00'

config wifi-iface
	option device 'radio2'
	option network 'lan'
	option mode 'ap'
	option ssid '5G-L'
	option encryption 'wpa2'
	option auth_server '192.168.1.3'
	option auth_secret 'NAS'
	option nasid '1'`

**Comment by Halry** [comment]
I had flashed back to OpenWrt 15.05(not the 15.05.1),everything works fine.But not working in lede,openwrt 15.05.1,openwrt trunk

**Comment by Halry** [comment]
Sorry,that is a once success.No success tried after disconnected

**Comment by ignisf** [comment]
Are you experiencing the issue with a [current LEDE snapshot](https://downloads.lede-project.org/snapshots/targets/), too?

**Comment by Halry** [comment]
Yes

**Comment by Halry** [comment]
And the signal is very bad.I had good signal when I was using stock.So right now I revert to stock.

**Comment by thess** [comment]
Moved to https://bugs.lede-project.org/index.php?do=details&task_id=133
