### ISSUE TITLE
compile error using the switch "-j" (eq. -j8) in the > r1493 +

### ISSUE THREAD

**Issue by build000** [lede-project/source#317]
I do not know whether it causes a package from a group of packages or the core of the project, which is why I put such information only observation.
Tested on version r1504 - identical .config built without a problem on version r1493. I add .config to illustrate the situation.
While construction of all “-j1” and unless the default “-j2” passes without a problem.
The system is ubuntu 16.04.1+ x64 (the current status of packages with the date of the notification).
I realize that such a description of the problem is too little - but I do not know how to pluck what is causing the problem compilation - definitely has to do with building a multi-threaded multi-core processor for x64 systems - so much is certain.

[.config.txt](https://github.com/lede-project/source/files/453998/default.config.txt)

**Comment by thess** [comment]
Closing this (did not follow instructions)

Please report LEDE system issues to: https://bugs.lede-project.org
LEDE/OpenWrt package issues: https://github.com/openwrt/packages/issues
