### ISSUE TITLE
Dragino Yun

### ISSUE THREAD

**Issue by rogueturnip** [lede-project/source#394]
Has anyone built this with the Dragino Yun?  Wondering if there is anything I have to do to make it build right.

**Comment by lfulcomer** [comment]
Some quick google-fu says https://github.com/dragino/openwrt-yun

**Comment by mkresin** [comment]
You either missed or you do not care about the note that was shown while you created the report:

> Please do not open any NEW issue here...

Please do not create bug reports for support requests! Use the mailing list instead.
