### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by juyyao** [lede-project/source#401]
juyyao@debian:~/down/lede$ make with -j1 V=s
File [/home/juyyao/down/lede/tmp/.config] already exists, skipping it !
/!\ THE FOLLOWING FILES WERE *NOT* SUCCESSFULY COPIED:
	- /home/juyyao/down/lede/.config
--

Please check journal: /home/juyyao/.gcp/journal
make[1]: Entering directory '/home/juyyao/down/lede'
make[1]: *** No rule to make target 'with'.  Stop.
make[1]: Leaving directory '/home/juyyao/down/lede'
/home/juyyao/down/lede/include/toplevel.mk:193: recipe for target 'with' failed
make: *** [with] Error 2

I am new to this,can someone help me?
thx

**Comment by bobafetthotmail** [comment]
wrong command.
right command is
**make -j1 V=s**

also please use the bugtracker for issues. https://bugs.lede-project.org/

**Comment by juyyao** [comment]
foolish me~
thx
