### ISSUE TITLE
lantiq: Add support Zyxel P-2812HNU-F1 vT

### ISSUE THREAD

**Issue by didzejdomin** [lede-project/source#492]
Please add support for Zyxel P-2812HNU-F1 vT.
It's model exactly like P-2812HNU-F1 but with RT3092L wireless chip on board (like F3 version). .dts file should looks like (100% tested - wireless and info leds works ok):

/dts-v1/;

/include/ "P2812HNUFX.dtsi"

/ {
	model = "P2812HNUF1 - ZyXEL P-2812HNU-F1";

	fpi@10000000 {
		localbus@0 {
			nand-parts@0 {
				compatible = "gen_nand", "lantiq,nand-xway";
				lantiq,cs = <1>;
				bank-width = <2>;
				reg = <0 0x0 0x2000000>;
				#address-cells = <1>;
				#size-cells = <1>;

				partition@0 {
					label = "uboot";
					reg = <0x00000 0x40000>;
				};
				partition@40000 {
					label = "uboot-env";
					reg = <0x40000 0x20000>;
				};
				partition@60000 {
					label = "kernel";
					reg = <0x60000 0x200000>;
				};
				partition@260000 {
					label = "ubi";
					reg = <0x260000 0x7da0000>;
				};
			};
		};
	};

	ralink_eep {
		compatible = "ralink,eeprom";
		ralink,eeprom = "RT3092.eeprom";
	};
};

**Comment by thess** [comment]
Closing this (did not follow instructions)

- Submit patches via mailing-list or Pull Request here.
- Please report LEDE system issues to: https://bugs.lede-project.org

LEDE/OpenWrt package issues: https://github.com/openwrt/packages/issues
