### ISSUE TITLE
dnsmasq-full doesn't set ipsets 

### ISSUE THREAD

**Issue by etomm** [lede-project/source#493]
In current lede master.

Installed the package dnsmasq-full.

Create some ipset in dnsmasq section of dhcp:
```
config dnsmasq
        ...
        list ipset '/hulu.com/hulu'
        list ipset '/huluim.com/huluim/'
```

I was expecting to see them listed in iptset list after restarting dnsmasq or rebooting the router.

In OpenWRT CC 15.05 this was the effective behaviour.

In Lede seems that you must create them manually.

**Comment by thess** [comment]
Closing this (did not follow instructions)

Please report LEDE system issues to: https://bugs.lede-project.org
LEDE/OpenWrt package issues: https://github.com/openwrt/packages/issues
