### ISSUE TITLE
Xiaomi Mi Router 3 Support?

### ISSUE THREAD

**Issue by sturze** [lede-project/source#59]
Hey! 
is the Xiaomi Mi Wifi Router 3 supported? 
or will it be?

its pretty cheap and i use them as accesspoints

Teardown:
http://www.cnx-software.com/2016/04/20/xiaomi-mi-wifi-3-router-unboxing-teardown-and-serial-console/

Hardware Desc:
http://xiaomi-mi.us/mi-wifi/xiaomi-mi-wifi-router-3-white/

**Comment by blogic** [comment]
this is a feature request and not an issue. if you want the support added, you will need get a unit, create a patch and send it as a PR.

**Comment by sturze** [comment]
sorry... how can i create a feature request? i have one of these Routers at home, but how can i create a patch?!
