### ISSUE TITLE
Compile Error - include/toplevel.mk:193 - how to use proxy for download ?

### ISSUE THREAD

**Issue by ds2k5** [lede-project/source#71]
Hello,
got source from github today.
Got compile error.

 make[3] -C tools/sstrip compile
 make[3] -C tools/sstrip install
 make[3] -C tools/make-ext4fs compile
make -r world: build failed. Please re-run make with -j1 V=s to see what's going on
/home/user01/source/include/toplevel.mk:193: recipe for target 'world' failed

 make -j1 V=s

show that download e2fsprogs failed.

how to use proxy for download?
proxychains did not work by some reason.

**Comment by widora** [comment]
You can manually download the e2fsprogs, then in the DL directory

**Comment by ds2k5** [comment]
Thanks widora,
but there are some other packages too.

for example: mtd-utils
i downloaded the source an extract to ../source/tools/mtd-utils
but did not work:

make -j1 V=s
...
...

mkdir -p /home/user01/source/dl
SHELL= flock /home/user01/source/tmp/.mtd-utils-1.5.2-aea36417067dade75192bafa03af70b6eb2677b1.tar.gz.flock -c '	 echo "Checking out files from the git repository..."; mkdir -p /home/user01/source/tmp/dl && cd /home/user01/source/tmp/dl && rm -rf mtd-utils-1.5.2 && [ \! -d mtd-utils-1.5.2 ] && git clone git://git.infradead.org/mtd-utils.git mtd-utils-1.5.2 && (cd mtd-utils-1.5.2 && git checkout aea36417067dade75192bafa03af70b6eb2677b1 && git submodule update --init --recursive) && echo "Packing checkout..." && rm -rf mtd-utils-1.5.2/.git && 	tar czf /home/user01/source/tmp/dl/mtd-utils-1.5.2-aea36417067dade75192bafa03af70b6eb2677b1.tar.gz mtd-utils-1.5.2 && mv /home/user01/source/tmp/dl/mtd-utils-1.5.2-aea36417067dade75192bafa03af70b6eb2677b1.tar.gz /home/user01/source/dl/ && rm -rf mtd-utils-1.5.2; '
Checking out files from the git repository...
Cloning into 'mtd-utils-1.5.2'...
fatal: Unable to look up git.infradead.org (port 9418) (Name or service not known)
Makefile:60: recipe for target '/home/user01/source/dl/mtd-utils-1.5.2-aea36417067dade75192bafa03af70b6eb2677b1.tar.gz' failed
make[3]: *** [/home/user01/source/dl/mtd-utils-1.5.2-aea36417067dade75192bafa03af70b6eb2677b1.tar.gz] Error 128
make[3]: Leaving directory '/home/user01/source/tools/mtd-utils'
tools/Makefile:134: recipe for target 'tools/mtd-utils/compile' failed
make[2]: *** [tools/mtd-utils/compile] Error 2
make[2]: Leaving directory '/home/user01/source'
tools/Makefile:133: recipe for target '/home/user01/source/staging_dir/target-i386_i486_musl-1.1.14/stamp/.tools_install_yynyynynynyyyyyyynyyynyyyyyyyyynyyyyynyyynynnyyynnnyy' failed
make[1]: *** [/home/user01/source/staging_dir/target-i386_i486_musl-1.1.14/stamp/.tools_install_yynyynynynyyyyyyynyyynyyyyyyyyynyyyyynyyynynnyyynnnyy] Error 2
make[1]: Leaving directory '/home/user01/source'
/home/user01/source/include/toplevel.mk:193: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by blogic** [comment]
are you behind some corporate firewall ?

**Comment by ds2k5** [comment]
yes, no dns, no direct access to internet. only with http-proxy

**Comment by blogic** [comment]
that would explain why dns fails. you will also need git ports open to compile.
