### ISSUE TITLE
busybox: ping6 doesn't show neighbors when doing ping ff02::1%br-lan

### ISSUE THREAD

**Issue by lynxis** [lede-project/source#75]
<pre>
root@lede:~# ping6 ff02::1%br-lan
PING ff02::1%br-lan (ff02::1%br-lan): 56 data bytes
64 bytes from fe80::ea94:f6ff:fe23:d11e: seq=0 ttl=64 time=0.742 ms
</pre>
it only show it's own ipv6 address, but not any neighbor icmp responses.

**Comment by bittorf** [comment]
this is a known issue and belongs to the busybox bugtracker - please close this one.

**Comment by jow-** [comment]
@bittorf do you have some url we can refer to when closing this issue?

**Comment by bittorf** [comment]
sorry, yes: http://lists.busybox.net/pipermail/busybox-cvs/2011-May/032559.html

**Comment by lynxis** [comment]
works now on x86. will test later on ar71xx.

**Comment by lynxis** [comment]
works.
