### ISSUE TITLE
fw: can not ping the router via link local on all nodes multicast `ping6 ff02:1%eth0` 

### ISSUE THREAD

**Issue by lynxis** [lede-project/source#76]
without firewall the device answer.

**Comment by DPini** [comment]
I am able to reproduce this bug.
I have been looking into it, and I have found that deleting this rule `ip6tables -t filter -D OUTPUT -m id --id 0x66773300 -m conntrack --ctstate INVALID -j DROP` from the ip6tables firewall allows to ping it with it's IPv6 Link-local address

Comparing the output of `fw3 -6 print` (LEDE trunk)  with a router running OpenWRT Breaking Barrier, this rule doesn't appear.

Attached you can find the outputs of fw3

[lede_fw3_6_print.txt](https://github.com/lede-project/source/files/327561/lede_fw3_6_print.txt)
[openwrt_BB_fw3_6_print.txt](https://github.com/lede-project/source/files/327562/openwrt_BB_fw3_6_print.txt)

**Comment by jow-** [comment]
You should be able to inhibit the drop rule by using `option drop_invalid 0` in the defaults section.

**Comment by lynxis** [comment]
@jow- any idea how we can fix this with `option drop_invalid 1`?
Is this is kernel bug, that the kernel does not track the state of icmp6 mcast replies correct?

**Comment by thess** [comment]
Issue moved to [FS#154](https://bugs.lede-project.org/index.php?do=details&task_id=154)
