### ISSUE TITLE
json_filter: integer overflow

### ISSUE THREAD

**Issue by lynxis** [lede-project/source#78]
while trying to parse the statistics with ash I ran into an integer overflow.
jsonfilter returns 2147483647 (0x7fffffff). But it should be 3165840995

<pre>
CACHE=ubus call network.device status '{ "name": "eth1" }'
jsonfilter -s "$CACHE" -e "rx_bytes=$.statistics.rx_bytes"
export rx_bytes=2147483647;
echo $CACHE
</pre>

<pre>
{
	"external": false,
	"present": true,
	"type": "Network device",
	"up": true,
	"carrier": true,
	"link-advertising": [
		"10H",
		"10F",
		"100H",
		"100F",
		"1000F"
	],
	"link-supported": [
		"10H",
		"10F",
		"100H",
		"100F",
		"1000F"
	],
	"speed": "100F",
	"mtu": 1500,
	"mtu6": -1,
	"macaddr": "60:e3:22:12:34:56",
	"txqueuelen": 1000,
	"promisc": false,
	"rpfilter": 0,
	"acceptlocal": false,
	"igmpversion": 0,
	"neigh4reachabletime": 30000,
	"neigh6reachabletime": 0,
	"statistics": {
		"collisions": 0,
		"rx_frame_errors": 0,
		"tx_compressed": 0,
		"multicast": 0,
		"rx_length_errors": 0,
		"tx_dropped": 0,
		"rx_bytes": 3165840995,
		"rx_missed_errors": 0,
		"tx_errors": 0,
		"rx_compressed": 0,
		"rx_over_errors": 0,
		"tx_fifo_errors": 0,
		"rx_crc_errors": 0,
		"rx_packets": 3326986,
		"tx_heartbeat_errors": 0,
		"rx_dropped": 3025,
		"tx_aborted_errors": 0,
		"tx_packets": 784417,
		"rx_errors": 0,
		"tx_bytes": 148145012,
		"tx_window_errors": 0,
		"rx_fifo_errors": 1,
		"tx_carrier_errors": 0
	}
}

</pre>

**Comment by jow-** [comment]
Fixed with 83390271f9d9495fb394ea654bb1a959fb9ca4ec
