### ISSUE TITLE
Link to dev.openwrt.org in Luci's Network/Diagnostics default fields

### ISSUE THREAD

**Issue by stangri** [lede-project/source#90]
If you have Luci installed and you hit /cgi-bin/luci/admin/network/diagnostics the default field values are dev.openwrt.org. Since the OpenWrt infrastructure is known to have gown down in the past, I suggest those are replaced with lede-project names or something else stable and world-wide accessible.

**Comment by miltador** [comment]
Same to the NTP servers in the System tab. Currently there are OpenWrt NTP servers set by default.

**Comment by LipkeGu** [comment]
@miltador you can simply replace these servers with ntp.org servers ... these server are mainly the same as:

use this in /etc/config/system
```
server 0.pool.ntp.org
server 1.pool.ntp.org
server 2.pool.ntp.org
server 3.pool.ntp.org
```

**Comment by miltador** [comment]
@LipkeGu thanks, but the question is: should OpenWRT NTP pool servers be set as default ones?

**Comment by jow-** [comment]
I contacted ntp.org and try to register a "lede" vendor zone so that we can use "0.lede.pool.ntp.org" etc. Projects, open source operating systems etc. are strongly encouraged to use vendor zones.

**Comment by jow-** [comment]
Our vendor zone got approved, I'll wait another day for the `*.lede.pool.ntp.org` to be widely available, then I'll change the defaults.

**Comment by miltador** [comment]
@jow-, good news!
But what about this issue? Link to dev.openwrt.org I mean.

**Comment by jow-** [comment]
Will change it too, soon.

**Comment by feckert** [comment]
Would it not be better to make the value for diagnositc configurable as the ntp server. So every on can config there own url he want to verify with the diagnositc tools?

**Comment by feckert** [comment]
I think we can close this issue
[I have added a config section to customizable the url](https://github.com/openwrt/luci/commit/8b07a65117b8a9ebbed801579d34ae8f51255868)

**Comment by thess** [comment]
Issue moved to [FS#156](https://bugs.lede-project.org/index.php?do=details&task_id=156)
