### ISSUE TITLE
/dev/tty and /dev/snd have wrong permissions

### ISSUE THREAD

**Issue by neheb** [lede-project/source#91]
/dev/tty is 644 when it should be 666. it causes an error with openssh.

/dev/snd is 644 when it should be 666 and is owned by root:root when it should be owned by root:audio

**Comment by blogic** [comment]
@jow-  how about this for the tty issue ?

https://git.lede-project.org/?p=lede/blogic/staging.git;a=commit;h=b1d11b8d18602bc0b1f7270fc491a5696ab0b547

**Comment by neheb** [comment]
664? My use case is using SSH with a non-root user. 664 still gives the
error. On arch and Ubuntu the permissions are 667

**Comment by neheb** [comment]
for reference, this is before and after plugging in the sound card:

root@OpenWrt:~# ls -l /dev/snd/
crw-r--r--    1 root     root      116,  33 Jun  6 06:46 timer

root@OpenWrt:~# ls -l /dev/snd/
/dev/snd/:
crw-r--r--    1 root     root      116,   0 Jun  7 19:56 controlC0
crw-r--r--    1 root     root      116,  16 Jun  7 19:56 pcmC0D0p
crw-r--r--    1 root     root      116,  33 Jun  6 06:46 timer

**Comment by blogic** [comment]
do we even have an audio group ?

**Comment by neheb** [comment]
i see audio:x:29: in /etc/groups. not sure if some application adds it.

**Comment by blogic** [comment]
we actually do have an audio group. unfortunately our hotplug service cannot handle groups yet.

**Comment by blogic** [comment]
@neheb we have a bugtracking system now. can you add a ticket there regarding hotplug events setting up user groups of device nodes ? the other stuff is now fixed in source.git.
